server:
  port: 8080
spring:
  datasource:
    url:  ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/captialsbank_prod}
    username: ${SPRING_DATASOURCE_USERNAME:root}     # always env variables in prod
    password: ${SPRING_DATASOURCE_PASSWORD:Pranathi@2005}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20            # higher pool for prod load
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate               # NEVER update/create in prod
    show-sql: false                    # never log SQL in prod
  devtools:
    restart:
      enabled: false

logging:
  level:
    root: WARN                         # minimal logging in prod
    com.insurance.account: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

accounts:
  message: "welcome to the capitals bank related to production apis"
  contact-details:
    name: "Raju -Production "
    email: "raju@capitalsbank.com"
    onCallSupport:
      - "9876543210"
      - "9876543211"
