server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/captialsbank}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: '{cipher}c6e24f77874b1173345e1ee506d44aa3b05796d556b8c68d58db632bc3639618'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

accounts:
  message: "Welcome to the updated Capitals Bank APIs"

  contact-details:
    name: "Pavan Kumar - Developer"
    email: "pavan.kumar@capitalsbank.com"
    phone: "+91-9876543210"
    on-call-support:
      - "9876543210"
      - "9876543211"

  bank-details:
    bank-name: "Capitals Bank"
    branch-name: "Bengaluru Technology Branch"
    ifsc-code: "CAPB0002001"

    address:
      building-name: "Capitals Technology Centre"
      street: "Beside Manaytha Tech PArk"
      area: "WhiteField"
      city: "Bengaluru"
      district: "Bengaluru Urban"
      state: "Karnataka"
      country: "India"
      postal-code: "560037"

info:
  app:
    name: "Capitals Bank Account Service"
    environment: "Development"
    version: "1.0.0"
