server:
  port: 8081

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:mysql://localhost:3306/captials_transactions
    username: root
    password: c6e24f77874b1173345e1ee506d44aa3b05796d556b8c68d58db632bc3639618
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: CapitalsTransactionPool
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    openfeign:
      client:
        config:
          capitals-bank:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}

transaction:
  message: "welcome to the capitals bank transaction dev apis"
  contactDetails:
    name: "Ravi Kumar - Developer"
    email: "Ravi.kumar@capitalsbank.com"
    onCallSupport:
      - "7684743900"
      - "7684743901"

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
  endpoint:
    health:
      show-details: always
